import { EventType, EventTypeConfig } from '@/types';

export const EVENT_TYPES: EventTypeConfig[] = [
  {
    type: 'sweet15',
    label: 'Sweet 15 / Quinceañera',
    description: 'Celebrate this milestone with a stunning rose & gold themed website featuring your court of honor.',
    price: 14900,
    icon: 'Crown',
    color: 'rose',
    fields: [
      { key: 'church_name', label: 'Church Name', type: 'text', placeholder: 'e.g. St. Mary\'s Cathedral' },
      { key: 'church_address', label: 'Church Address', type: 'address', placeholder: 'Full church address' },
      { key: 'church_time', label: 'Church Time', type: 'time' },
      { key: 'venue_name', label: 'Venue Name', type: 'text', placeholder: 'e.g. Grand Ballroom' },
      { key: 'venue_address', label: 'Venue Address', type: 'address', placeholder: 'Full address' },
      { key: 'ceremony_time', label: 'Ceremony Time', type: 'time' },
      { key: 'reception_start', label: 'Reception Start Time', type: 'time' },
      { key: 'reception_end', label: 'Reception End Time', type: 'time' },
      { key: 'dinner_start', label: 'Dinner Start Time', type: 'time' },
      { key: 'dinner_end', label: 'Dinner End Time', type: 'time' },
      { key: 'honoree_name', label: 'Quinceañera Name', type: 'text', placeholder: 'Name of the honoree', required: true },
      { key: 'theme', label: 'Party Theme', type: 'text', placeholder: 'e.g. Enchanted Garden' },
      { key: 'godparents', label: 'Godparents (Padrinos)', type: 'textarea', placeholder: 'List your padrinos and madrinas' },
      { key: 'court_of_honor', label: 'Court of Honor', type: 'textarea', placeholder: 'List your damas and chambelanes' },
      { key: 'special_message', label: 'Special Message', type: 'textarea', placeholder: 'A message to your guests' },
      { key: 'dress_code', label: 'Dress Code', type: 'text', placeholder: 'e.g. Formal / Semi-formal' },
      { key: 'parent_names', label: 'Parent Names', type: 'text', placeholder: 'Proud parents' },
      { key: 'registry_url', label: 'Registry Link', type: 'url', placeholder: 'https://...' },
    ],
  },
  {
    type: 'wedding',
    label: 'Wedding',
    description: 'Share your love story with an elegant ivory & sage wedding website with RSVP and registry.',
    price: 14900,
    icon: 'Heart',
    color: 'emerald',
    fields: [
      { key: 'partner1_name', label: 'Partner 1 Name', type: 'text', required: true },
      { key: 'partner2_name', label: 'Partner 2 Name', type: 'text', required: true },
      { key: 'church_name', label: 'Church Name', type: 'text', placeholder: 'e.g. St. Mary\'s Cathedral' },
      { key: 'church_address', label: 'Church Address', type: 'address', placeholder: 'Full church address' },
      { key: 'church_time', label: 'Church Time', type: 'time' },
      { key: 'venue_name', label: 'Venue Name', type: 'text', placeholder: 'e.g. Rose Garden Estate' },
      { key: 'venue_address', label: 'Venue Address', type: 'address', placeholder: 'Full address' },
      { key: 'ceremony_time', label: 'Ceremony Time', type: 'time' },
      { key: 'reception_start', label: 'Reception Start Time', type: 'time' },
      { key: 'reception_end', label: 'Reception End Time', type: 'time' },
      { key: 'dinner_start', label: 'Dinner Start Time', type: 'time' },
      { key: 'dinner_end', label: 'Dinner End Time', type: 'time' },
      { key: 'godparents', label: 'Godparents (Padrinos)', type: 'textarea', placeholder: 'List your padrinos and madrinas' },
      { key: 'our_story', label: 'Our Story', type: 'textarea', placeholder: 'How did you two meet?' },
      { key: 'registry_url', label: 'Registry Link', type: 'url', placeholder: 'https://...' },
      { key: 'dress_code', label: 'Dress Code', type: 'text', placeholder: 'e.g. Black Tie' },
      { key: 'accommodations', label: 'Accommodations', type: 'textarea', placeholder: 'Hotel info for guests' },
      { key: 'special_message', label: 'Special Message', type: 'textarea', placeholder: 'A message to your guests' },
    ],
  },
  {
    type: 'birthday',
    label: 'Birthday',
    description: 'Throw the ultimate birthday bash with a vibrant, fun website that puts the spotlight on the guest of honor.',
    price: 5000,
    icon: 'Cake',
    color: 'violet',
    fields: [
      { key: 'birthday_person', label: 'Birthday Person', type: 'text', required: true },
      { key: 'turning_age', label: 'Turning Age', type: 'text', placeholder: 'e.g. 30' },
      { key: 'church_name', label: 'Church Name', type: 'text', placeholder: 'e.g. St. Mary\'s Cathedral' },
      { key: 'church_address', label: 'Church Address', type: 'address', placeholder: 'Full church address' },
      { key: 'church_time', label: 'Church Time', type: 'time' },
      { key: 'venue_name', label: 'Venue Name', type: 'text' },
      { key: 'venue_address', label: 'Venue Address', type: 'address' },
      { key: 'party_time', label: 'Party Time', type: 'time' },
      { key: 'theme', label: 'Party Theme', type: 'text', placeholder: 'e.g. 80s Retro' },
      { key: 'special_message', label: 'Special Message', type: 'textarea', placeholder: 'A message for your guests' },
      { key: 'dress_code', label: 'Dress Code', type: 'text' },
    ],
    optionalSections: [
      {
        id: 'reception',
        label: 'Reception',
        addOnPrice: 1000,
        fields: [
          { key: 'reception_start', label: 'Reception Start Time', type: 'time' },
          { key: 'reception_end', label: 'Reception End Time', type: 'time' },
        ],
      },
      {
        id: 'dinner',
        label: 'Dinner / Lunch',
        addOnPrice: 1000,
        fields: [
          { key: 'dinner_start', label: 'Start Time', type: 'time' },
          { key: 'dinner_end', label: 'End Time', type: 'time' },
        ],
      },
    ],
  },
  {
    type: 'baby_shower',
    label: 'Baby Shower',
    description: 'Welcome the little one with a soft pastel baby shower page featuring registry and wishes.',
    price: 5000,
    icon: 'Baby',
    color: 'sky',
    fields: [
      { key: 'parent_names', label: 'Parent Name(s)', type: 'text', required: true },
      { key: 'baby_name', label: 'Baby Name (if chosen)', type: 'text', placeholder: 'Optional' },
      { key: 'due_date', label: 'Baby Shower Date', type: 'date' },
      { key: 'shower_time', label: 'Shower Time', type: 'time' },
      { key: 'theme', label: 'Theme', type: 'text', placeholder: 'e.g. Woodland Animals' },
      { key: 'registry_url', label: 'Registry Link', type: 'url', placeholder: 'https://...' },
      { key: 'special_message', label: 'Message to Guests', type: 'textarea' },
    ],
    optionalSections: [
      {
        id: 'reception',
        label: 'Reception',
        addOnPrice: 1000,
        fields: [
          { key: 'reception_venue', label: 'Venue Name', type: 'text', placeholder: 'e.g. Grand Ballroom' },
          { key: 'reception_address', label: 'Venue Address', type: 'address' },
          { key: 'reception_start', label: 'Reception Start Time', type: 'time' },
          { key: 'reception_end', label: 'Reception End Time', type: 'time' },
        ],
      },
      {
        id: 'dinner',
        label: 'Dinner / Lunch',
        addOnPrice: 1000,
        fields: [
          { key: 'dinner_venue', label: 'Venue Name', type: 'text', placeholder: 'e.g. Grand Ballroom' },
          { key: 'dinner_address', label: 'Venue Address', type: 'address' },
          { key: 'dinner_start', label: 'Start Time', type: 'time' },
          { key: 'dinner_end', label: 'End Time', type: 'time' },
        ],
      },
    ],
  },
  {
    type: 'valentines',
    label: "Valentine's Day",
    description: 'Send a sweet Valentine\'s card to someone special with a personalized message.',
    price: 5000,
    icon: 'Heart',
    color: 'rose',
    fields: [
      { key: 'birthday_person', label: 'To', type: 'text', required: true },
      { key: 'special_message', label: 'Your Message', type: 'textarea' },
    ],
    optionalSections: [
      {
        id: 'reception',
        label: 'Reception / Gathering',
        addOnPrice: 1000,
        fields: [
          { key: 'reception_venue', label: 'Venue', type: 'text', placeholder: 'e.g. The Cheesecake Factory' },
          { key: 'reception_address', label: 'Address', type: 'address' },
          { key: 'reception_start', label: 'Start Time', type: 'time' },
          { key: 'reception_end', label: 'End Time', type: 'time' },
        ],
      },
      {
        id: 'dinner',
        label: 'Dinner / Lunch',
        addOnPrice: 1000,
        fields: [
          { key: 'dinner_venue', label: 'Venue', type: 'text', placeholder: 'e.g. The Cheesecake Factory' },
          { key: 'dinner_address', label: 'Address', type: 'address' },
          { key: 'dinner_start', label: 'Start Time', type: 'time' },
          { key: 'dinner_end', label: 'End Time', type: 'time' },
        ],
      },
    ],
  },
  {
    type: 'mothers_day',
    label: "Mother's Day",
    description: 'Celebrate Mom with a beautiful personalized card she\'ll treasure.',
    price: 5000,
    icon: 'Heart',
    color: 'pink',
    fields: [
      { key: 'birthday_person', label: 'To', type: 'text', required: true },
      { key: 'special_message', label: 'Your Message', type: 'textarea' },
    ],
    optionalSections: [
      {
        id: 'reception',
        label: 'Reception / Gathering',
        addOnPrice: 1000,
        fields: [
          { key: 'reception_venue', label: 'Venue', type: 'text', placeholder: 'e.g. The Cheesecake Factory' },
          { key: 'reception_address', label: 'Address', type: 'address' },
          { key: 'reception_start', label: 'Start Time', type: 'time' },
          { key: 'reception_end', label: 'End Time', type: 'time' },
        ],
      },
      {
        id: 'dinner',
        label: 'Dinner / Lunch',
        addOnPrice: 1000,
        fields: [
          { key: 'dinner_venue', label: 'Venue', type: 'text', placeholder: 'e.g. The Cheesecake Factory' },
          { key: 'dinner_address', label: 'Address', type: 'address' },
          { key: 'dinner_start', label: 'Start Time', type: 'time' },
          { key: 'dinner_end', label: 'End Time', type: 'time' },
        ],
      },
    ],
  },
  {
    type: 'fathers_day',
    label: "Father's Day",
    description: 'Show Dad some love with a personalized card just for him.',
    price: 5000,
    icon: 'Gift',
    color: 'blue',
    fields: [
      { key: 'birthday_person', label: 'To', type: 'text', required: true },
      { key: 'special_message', label: 'Your Message', type: 'textarea' },
    ],
    optionalSections: [
      {
        id: 'reception',
        label: 'Reception / Gathering',
        addOnPrice: 1000,
        fields: [
          { key: 'reception_venue', label: 'Venue', type: 'text', placeholder: 'e.g. The Cheesecake Factory' },
          { key: 'reception_address', label: 'Address', type: 'address' },
          { key: 'reception_start', label: 'Start Time', type: 'time' },
          { key: 'reception_end', label: 'End Time', type: 'time' },
        ],
      },
      {
        id: 'dinner',
        label: 'Dinner / Lunch',
        addOnPrice: 1000,
        fields: [
          { key: 'dinner_venue', label: 'Venue', type: 'text', placeholder: 'e.g. The Cheesecake Factory' },
          { key: 'dinner_address', label: 'Address', type: 'address' },
          { key: 'dinner_start', label: 'Start Time', type: 'time' },
          { key: 'dinner_end', label: 'End Time', type: 'time' },
        ],
      },
    ],
  },
];

export const CARD_EVENT_TYPES: EventType[] = ['valentines', 'mothers_day', 'fathers_day'];

export function getEventTypeConfig(type: string): EventTypeConfig | undefined {
  return EVENT_TYPES.find((et) => et.type === type);
}

