import { EventType, ThemeVariant } from '@/types';

const themes: ThemeVariant[] = [
  // ═══════════════════════════════════════
  // WEDDING (9 free + 3 premium = 12)
  // ═══════════════════════════════════════
  {
    id: 'wedding-ivory-sage',
    name: 'Ivory & Sage',
    description: 'Timeless elegance with warm ivory and sage green',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#faf8f5',
      surface: '#ffffff',
      text: '#1c1917',
      textSecondary: '#78716c',
      accent: '#5f7a61',
      accentText: '#ffffff',
      hero: '#5f7a61',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-romantic-blush',
    name: 'Romantic Blush',
    description: 'Soft pinks and warm rose tones',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#1c1917',
      textSecondary: '#9d7a8c',
      accent: '#be185d',
      accentText: '#ffffff',
      hero: '#9f1239',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-navy-gold',
    name: 'Navy & Gold',
    description: 'Rich navy blue with warm gold accents',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f8fafc',
      textSecondary: '#94a3b8',
      accent: '#d4a843',
      accentText: '#0f172a',
      hero: '#1e3a5f',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-dusty-rose',
    name: 'Dusty Rose',
    description: 'Muted mauve and dusty rose tones',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#faf5f5',
      surface: '#ffffff',
      text: '#44403c',
      textSecondary: '#a8a29e',
      accent: '#b5838d',
      accentText: '#ffffff',
      hero: '#8e6c7d',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-garden-green',
    name: 'Garden Green',
    description: 'Lush garden greens with floral warmth',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#f0fdf4',
      surface: '#ffffff',
      text: '#14532d',
      textSecondary: '#4ade80',
      accent: '#166534',
      accentText: '#ffffff',
      hero: '#14532d',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-lavender',
    name: 'Lavender Dreams',
    description: 'Soft lavender and purple pastels',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#faf5ff',
      surface: '#ffffff',
      text: '#3b0764',
      textSecondary: '#a855f7',
      accent: '#7c3aed',
      accentText: '#ffffff',
      hero: '#581c87',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-terracotta',
    name: 'Terracotta',
    description: 'Earthy terracotta with warm neutrals',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fef3e2',
      surface: '#ffffff',
      text: '#431407',
      textSecondary: '#b45309',
      accent: '#c2410c',
      accentText: '#ffffff',
      hero: '#9a3412',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-classic-black',
    name: 'Classic Black & White',
    description: 'Timeless monochrome sophistication',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#ffffff',
      surface: '#f5f5f5',
      text: '#171717',
      textSecondary: '#737373',
      accent: '#171717',
      accentText: '#ffffff',
      hero: '#171717',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-ocean-blue',
    name: 'Ocean Blue',
    description: 'Coastal blues and sandy neutrals',
    eventType: 'wedding',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#f0f9ff',
      surface: '#ffffff',
      text: '#0c4a6e',
      textSecondary: '#38bdf8',
      accent: '#0369a1',
      accentText: '#ffffff',
      hero: '#075985',
      heroText: '#ffffff',
    },
  },
  // Premium wedding themes
  {
    id: 'wedding-modern-minimal',
    name: 'Modern Minimalist',
    description: 'Clean lines with sophisticated minimal layout',
    eventType: 'wedding',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#ffffff',
      surface: '#fafafa',
      text: '#18181b',
      textSecondary: '#71717a',
      accent: '#18181b',
      accentText: '#ffffff',
      hero: '#18181b',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-split-elegance',
    name: 'Split Elegance',
    description: 'Dramatic split-screen with emerald tones',
    eventType: 'wedding',
    isPremium: true,
    layout: 'split',
    colors: {
      background: '#f5f5f4',
      surface: '#ffffff',
      text: '#1c1917',
      textSecondary: '#78716c',
      accent: '#065f46',
      accentText: '#ffffff',
      hero: '#064e3b',
      heroText: '#ffffff',
    },
  },
  {
    id: 'wedding-minimal-blush',
    name: 'Minimal Blush',
    description: 'Minimal layout with soft romantic blush',
    eventType: 'wedding',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#fff1f2',
      surface: '#ffffff',
      text: '#881337',
      textSecondary: '#e11d48',
      accent: '#be123c',
      accentText: '#ffffff',
      hero: '#9f1239',
      heroText: '#ffffff',
    },
  },

  // ═══════════════════════════════════════
  // BIRTHDAY (9 free + 3 premium = 12)
  // ═══════════════════════════════════════
  {
    id: 'birthday-vibrant-purple',
    name: 'Vibrant Purple',
    description: 'Bold purple energy with yellow highlights',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#2e1065',
      surface: '#3b0764',
      text: '#ffffff',
      textSecondary: '#c4b5fd',
      accent: '#eab308',
      accentText: '#1c1917',
      hero: '#4c1d95',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-neon-party',
    name: 'Neon Party',
    description: 'Electric neon on a dark background',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#0f172a',
      surface: '#1e293b',
      text: '#ffffff',
      textSecondary: '#94a3b8',
      accent: '#06b6d4',
      accentText: '#ffffff',
      hero: '#0f172a',
      heroText: '#22d3ee',
    },
  },
  {
    id: 'birthday-hot-pink',
    name: 'Hot Pink',
    description: 'Vibrant hot pink with dark contrast',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#500724',
      surface: '#831843',
      text: '#ffffff',
      textSecondary: '#f9a8d4',
      accent: '#ec4899',
      accentText: '#ffffff',
      hero: '#9d174d',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-tropical',
    name: 'Tropical',
    description: 'Bright tropical greens and oranges',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#052e16',
      surface: '#14532d',
      text: '#ffffff',
      textSecondary: '#86efac',
      accent: '#f97316',
      accentText: '#ffffff',
      hero: '#166534',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-retro-orange',
    name: 'Retro Orange',
    description: 'Warm retro vibes with orange and brown',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#431407',
      surface: '#7c2d12',
      text: '#ffffff',
      textSecondary: '#fdba74',
      accent: '#fb923c',
      accentText: '#431407',
      hero: '#9a3412',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-pastel-fun',
    name: 'Pastel Fun',
    description: 'Soft pastel colors for a playful look',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fefce8',
      surface: '#ffffff',
      text: '#422006',
      textSecondary: '#a16207',
      accent: '#a855f7',
      accentText: '#ffffff',
      hero: '#7e22ce',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-midnight-blue',
    name: 'Midnight Blue',
    description: 'Deep midnight blue with silver accents',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      textSecondary: '#94a3b8',
      accent: '#c0c0c0',
      accentText: '#0f172a',
      hero: '#0f172a',
      heroText: '#e2e8f0',
    },
  },
  {
    id: 'birthday-red-party',
    name: 'Red Party',
    description: 'Bold reds for an exciting celebration',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#450a0a',
      surface: '#7f1d1d',
      text: '#ffffff',
      textSecondary: '#fca5a5',
      accent: '#ef4444',
      accentText: '#ffffff',
      hero: '#991b1b',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-gold-glam',
    name: 'Gold Glam',
    description: 'Luxurious black and gold',
    eventType: 'birthday',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#171717',
      surface: '#262626',
      text: '#ffffff',
      textSecondary: '#a3a3a3',
      accent: '#d4a843',
      accentText: '#171717',
      hero: '#1c1917',
      heroText: '#d4a843',
    },
  },
  // Premium birthday themes
  {
    id: 'birthday-split-party',
    name: 'Split Screen Party',
    description: 'Eye-catching split-screen with vibrant gradients',
    eventType: 'birthday',
    isPremium: true,
    layout: 'split',
    colors: {
      background: '#1e1b4b',
      surface: '#312e81',
      text: '#ffffff',
      textSecondary: '#a5b4fc',
      accent: '#f472b6',
      accentText: '#ffffff',
      hero: '#312e81',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-minimal-mono',
    name: 'Minimal Mono',
    description: 'Sleek monochrome minimal layout',
    eventType: 'birthday',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#fafafa',
      surface: '#ffffff',
      text: '#171717',
      textSecondary: '#737373',
      accent: '#171717',
      accentText: '#ffffff',
      hero: '#171717',
      heroText: '#ffffff',
    },
  },
  {
    id: 'birthday-split-neon',
    name: 'Split Neon',
    description: 'Split layout with electric neon palette',
    eventType: 'birthday',
    isPremium: true,
    layout: 'split',
    colors: {
      background: '#020617',
      surface: '#0f172a',
      text: '#ffffff',
      textSecondary: '#38bdf8',
      accent: '#22d3ee',
      accentText: '#020617',
      hero: '#0c4a6e',
      heroText: '#ffffff',
    },
  },

  // ═══════════════════════════════════════
  // SWEET 15 (9 free + 3 premium = 12)
  // ═══════════════════════════════════════
  {
    id: 'sweet15-rose-gold',
    name: 'Rose & Gold',
    description: 'Classic quinceañera elegance with rose and gold',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#4c0519',
      surface: '#881337',
      text: '#ffffff',
      textSecondary: '#fda4af',
      accent: '#fbbf24',
      accentText: '#1c1917',
      hero: '#9f1239',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-teal-silver',
    name: 'Teal & Silver',
    description: 'Modern and fresh with teal and silver',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#042f2e',
      surface: '#134e4a',
      text: '#ffffff',
      textSecondary: '#99f6e4',
      accent: '#d4d4d8',
      accentText: '#18181b',
      hero: '#0f766e',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-royal-purple',
    name: 'Royal Purple',
    description: 'Regal purple with gold crown accents',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#3b0764',
      surface: '#581c87',
      text: '#ffffff',
      textSecondary: '#d8b4fe',
      accent: '#fbbf24',
      accentText: '#3b0764',
      hero: '#6b21a8',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-blush-cream',
    name: 'Blush & Cream',
    description: 'Delicate blush pink on warm cream',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#831843',
      textSecondary: '#9d174d',
      accent: '#db2777',
      accentText: '#ffffff',
      hero: '#9d174d',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-midnight-stars',
    name: 'Midnight Stars',
    description: 'Dark midnight sky with starry silver',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#0c0a09',
      surface: '#1c1917',
      text: '#ffffff',
      textSecondary: '#a8a29e',
      accent: '#e2e8f0',
      accentText: '#0c0a09',
      hero: '#1c1917',
      heroText: '#e2e8f0',
    },
  },
  {
    id: 'sweet15-coral-peach',
    name: 'Coral & Peach',
    description: 'Warm coral and peach sunset tones',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fff7ed',
      surface: '#ffffff',
      text: '#7c2d12',
      textSecondary: '#9a3412',
      accent: '#ea580c',
      accentText: '#ffffff',
      hero: '#c2410c',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-emerald-gold',
    name: 'Emerald & Gold',
    description: 'Luxurious emerald green with gold details',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#022c22',
      surface: '#064e3b',
      text: '#ffffff',
      textSecondary: '#6ee7b7',
      accent: '#d4a843',
      accentText: '#022c22',
      hero: '#065f46',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-sky-butterfly',
    name: 'Sky Butterfly',
    description: 'Light sky blue with butterfly-wing purple',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#eff6ff',
      surface: '#ffffff',
      text: '#1e3a5f',
      textSecondary: '#1e40af',
      accent: '#7c3aed',
      accentText: '#ffffff',
      hero: '#3b82f6',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-champagne',
    name: 'Champagne',
    description: 'Warm champagne gold on soft ivory',
    eventType: 'sweet15',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fffbeb',
      surface: '#ffffff',
      text: '#78350f',
      textSecondary: '#92400e',
      accent: '#b45309',
      accentText: '#ffffff',
      hero: '#92400e',
      heroText: '#ffffff',
    },
  },
  // Premium sweet15 themes
  {
    id: 'sweet15-minimal-elegance',
    name: 'Minimal Elegance',
    description: 'Sophisticated minimal layout with blush and cream',
    eventType: 'sweet15',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#fffbeb',
      surface: '#ffffff',
      text: '#451a03',
      textSecondary: '#92400e',
      accent: '#b45309',
      accentText: '#ffffff',
      hero: '#78350f',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-split-royal',
    name: 'Split Royal',
    description: 'Split-screen with regal purple and gold',
    eventType: 'sweet15',
    isPremium: true,
    layout: 'split',
    colors: {
      background: '#2e1065',
      surface: '#3b0764',
      text: '#ffffff',
      textSecondary: '#c4b5fd',
      accent: '#fbbf24',
      accentText: '#2e1065',
      hero: '#4c1d95',
      heroText: '#ffffff',
    },
  },
  {
    id: 'sweet15-minimal-rose',
    name: 'Minimal Rose',
    description: 'Minimal layout in soft rose tones',
    eventType: 'sweet15',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#fff1f2',
      surface: '#ffffff',
      text: '#881337',
      textSecondary: '#fb7185',
      accent: '#e11d48',
      accentText: '#ffffff',
      hero: '#9f1239',
      heroText: '#ffffff',
    },
  },

  // ═══════════════════════════════════════
  // BABY SHOWER (9 free + 3 premium = 12)
  // ═══════════════════════════════════════
  {
    id: 'baby-pastel-blue-pink',
    name: 'Pastel Blue & Pink',
    description: 'Soft pastel tones of blue and pink',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#f0f9ff',
      surface: '#ffffff',
      text: '#0c4a6e',
      textSecondary: '#7dd3fc',
      accent: '#0284c7',
      accentText: '#ffffff',
      hero: '#0369a1',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-neutral-woodland',
    name: 'Neutral Woodland',
    description: 'Warm earthy tones with a cozy, natural feel',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fefce8',
      surface: '#ffffff',
      text: '#422006',
      textSecondary: '#a16207',
      accent: '#65a30d',
      accentText: '#ffffff',
      hero: '#3f6212',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-soft-pink',
    name: 'Soft Pink',
    description: 'Gentle all-pink for a baby girl',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#831843',
      textSecondary: '#f472b6',
      accent: '#ec4899',
      accentText: '#ffffff',
      hero: '#be185d',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-sky-blue',
    name: 'Sky Blue',
    description: 'Classic light blue for a baby boy',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#eff6ff',
      surface: '#ffffff',
      text: '#1e3a5f',
      textSecondary: '#60a5fa',
      accent: '#2563eb',
      accentText: '#ffffff',
      hero: '#1d4ed8',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-sage-green',
    name: 'Sage Green',
    description: 'Gender-neutral sage green and cream',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#f0fdf4',
      surface: '#ffffff',
      text: '#14532d',
      textSecondary: '#4ade80',
      accent: '#16a34a',
      accentText: '#ffffff',
      hero: '#166534',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-sunny-yellow',
    name: 'Sunny Yellow',
    description: 'Bright and cheerful sunshine yellow',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fefce8',
      surface: '#ffffff',
      text: '#713f12',
      textSecondary: '#ca8a04',
      accent: '#eab308',
      accentText: '#422006',
      hero: '#a16207',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-lavender',
    name: 'Lavender',
    description: 'Soft lavender and lilac pastels',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#faf5ff',
      surface: '#ffffff',
      text: '#581c87',
      textSecondary: '#a855f7',
      accent: '#9333ea',
      accentText: '#ffffff',
      hero: '#7e22ce',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-mint-coral',
    name: 'Mint & Coral',
    description: 'Fresh mint green paired with warm coral',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#ecfdf5',
      surface: '#ffffff',
      text: '#064e3b',
      textSecondary: '#34d399',
      accent: '#f97316',
      accentText: '#ffffff',
      hero: '#047857',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-peach-cream',
    name: 'Peach & Cream',
    description: 'Warm peachy tones on soft cream',
    eventType: 'baby_shower',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fff7ed',
      surface: '#ffffff',
      text: '#7c2d12',
      textSecondary: '#fb923c',
      accent: '#ea580c',
      accentText: '#ffffff',
      hero: '#c2410c',
      heroText: '#ffffff',
    },
  },
  // Premium baby shower themes
  {
    id: 'baby-split-layout',
    name: 'Split Pastel',
    description: 'Modern split-screen with gentle pastels',
    eventType: 'baby_shower',
    isPremium: true,
    layout: 'split',
    colors: {
      background: '#faf5ff',
      surface: '#ffffff',
      text: '#581c87',
      textSecondary: '#a855f7',
      accent: '#9333ea',
      accentText: '#ffffff',
      hero: '#7e22ce',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-minimal-neutral',
    name: 'Minimal Neutral',
    description: 'Clean minimal layout with neutral tones',
    eventType: 'baby_shower',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#fafaf9',
      surface: '#ffffff',
      text: '#292524',
      textSecondary: '#78716c',
      accent: '#57534e',
      accentText: '#ffffff',
      hero: '#44403c',
      heroText: '#ffffff',
    },
  },
  {
    id: 'baby-split-blue',
    name: 'Split Blue',
    description: 'Split layout with ocean blue palette',
    eventType: 'baby_shower',
    isPremium: true,
    layout: 'split',
    colors: {
      background: '#eff6ff',
      surface: '#ffffff',
      text: '#1e3a5f',
      textSecondary: '#60a5fa',
      accent: '#3b82f6',
      accentText: '#ffffff',
      hero: '#1e40af',
      heroText: '#ffffff',
    },
  },
  // ═══════════════════════════════════════
  // VALENTINE'S DAY (3 free + 1 premium = 4)
  // ═══════════════════════════════════════
  {
    id: 'valentines-classic-red',
    name: 'Classic Red',
    description: 'Bold romantic red with warm tones',
    eventType: 'valentines',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#450a0a',
      surface: '#7f1d1d',
      text: '#ffffff',
      textSecondary: '#fca5a5',
      accent: '#f43f5e',
      accentText: '#ffffff',
      hero: '#991b1b',
      heroText: '#ffffff',
    },
  },
  {
    id: 'valentines-soft-blush',
    name: 'Soft Blush',
    description: 'Gentle pink and rose pastels',
    eventType: 'valentines',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fff1f2',
      surface: '#ffffff',
      text: '#881337',
      textSecondary: '#e11d48',
      accent: '#be123c',
      accentText: '#ffffff',
      hero: '#9f1239',
      heroText: '#ffffff',
    },
  },
  {
    id: 'valentines-dark-romance',
    name: 'Dark Romance',
    description: 'Deep burgundy with gold accents',
    eventType: 'valentines',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#1c1917',
      surface: '#292524',
      text: '#ffffff',
      textSecondary: '#a8a29e',
      accent: '#e11d48',
      accentText: '#ffffff',
      hero: '#0c0a09',
      heroText: '#fda4af',
    },
  },
  {
    id: 'valentines-minimal-love',
    name: 'Minimal Love',
    description: 'Clean minimal layout with romantic touches',
    eventType: 'valentines',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#831843',
      textSecondary: '#f472b6',
      accent: '#ec4899',
      accentText: '#ffffff',
      hero: '#be185d',
      heroText: '#ffffff',
    },
  },

  // ═══════════════════════════════════════
  // MOTHER'S DAY (3 free + 1 premium = 4)
  // ═══════════════════════════════════════
  {
    id: 'mothers-floral-pink',
    name: 'Floral Pink',
    description: 'Soft floral pinks for Mom',
    eventType: 'mothers_day',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#831843',
      textSecondary: '#db2777',
      accent: '#ec4899',
      accentText: '#ffffff',
      hero: '#9d174d',
      heroText: '#ffffff',
    },
  },
  {
    id: 'mothers-lavender',
    name: 'Lavender Garden',
    description: 'Calming lavender and soft purple',
    eventType: 'mothers_day',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#faf5ff',
      surface: '#ffffff',
      text: '#581c87',
      textSecondary: '#a855f7',
      accent: '#9333ea',
      accentText: '#ffffff',
      hero: '#7e22ce',
      heroText: '#ffffff',
    },
  },
  {
    id: 'mothers-rose-cream',
    name: 'Rose & Cream',
    description: 'Warm rose tones on soft cream',
    eventType: 'mothers_day',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#fff1f2',
      surface: '#ffffff',
      text: '#9f1239',
      textSecondary: '#fb7185',
      accent: '#e11d48',
      accentText: '#ffffff',
      hero: '#881337',
      heroText: '#ffffff',
    },
  },
  {
    id: 'mothers-minimal-floral',
    name: 'Minimal Floral',
    description: 'Elegant minimal layout with floral palette',
    eventType: 'mothers_day',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#fdf4ff',
      surface: '#ffffff',
      text: '#701a75',
      textSecondary: '#c026d3',
      accent: '#a21caf',
      accentText: '#ffffff',
      hero: '#86198f',
      heroText: '#ffffff',
    },
  },

  // ═══════════════════════════════════════
  // FATHER'S DAY (3 free + 1 premium = 4)
  // ═══════════════════════════════════════
  {
    id: 'fathers-classic-blue',
    name: 'Classic Blue',
    description: 'Strong navy blue with clean accents',
    eventType: 'fathers_day',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f8fafc',
      textSecondary: '#94a3b8',
      accent: '#3b82f6',
      accentText: '#ffffff',
      hero: '#1e3a5f',
      heroText: '#ffffff',
    },
  },
  {
    id: 'fathers-forest-green',
    name: 'Forest Green',
    description: 'Rich earthy greens for Dad',
    eventType: 'fathers_day',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#052e16',
      surface: '#14532d',
      text: '#ffffff',
      textSecondary: '#86efac',
      accent: '#22c55e',
      accentText: '#052e16',
      hero: '#166534',
      heroText: '#ffffff',
    },
  },
  {
    id: 'fathers-warm-earth',
    name: 'Warm Earth',
    description: 'Earthy brown and tan tones',
    eventType: 'fathers_day',
    isPremium: false,
    layout: 'classic',
    colors: {
      background: '#1c1917',
      surface: '#292524',
      text: '#fafaf9',
      textSecondary: '#a8a29e',
      accent: '#d97706',
      accentText: '#1c1917',
      hero: '#292524',
      heroText: '#fafaf9',
    },
  },
  {
    id: 'fathers-minimal-slate',
    name: 'Minimal Slate',
    description: 'Clean minimal layout with slate tones',
    eventType: 'fathers_day',
    isPremium: true,
    layout: 'minimal',
    colors: {
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      textSecondary: '#64748b',
      accent: '#334155',
      accentText: '#ffffff',
      hero: '#1e293b',
      heroText: '#ffffff',
    },
  },
];

export function getThemesForEventType(eventType: EventType): ThemeVariant[] {
  return themes.filter((t) => t.eventType === eventType);
}

export function getThemeById(themeId: string): ThemeVariant | undefined {
  return themes.find((t) => t.id === themeId);
}

export function getDefaultTheme(eventType: EventType): ThemeVariant {
  return themes.find((t) => t.eventType === eventType && !t.isPremium)!;
}
